{% set name = "vs2022" %}
{% set msvc_version = "14.37.17" %}

source:
  git_url: https://github.com/adriendelsalle/msvc-installer
  git_tag: improve-installer

package:
  name: {{ name|lower }}

build:
  number: 0
  skip: True  # [not win]
  script_env:
   - CONDA_BLD_REGEX_CHUNK_SIZE=15000

outputs:
  - name: {{ name }}-msvc-x64
    version: {{ msvc_version }}
    script: bld_vs2022.bat                      # [win]
    requirements:
      run:
        - {{ pin_subpackage('vs2022-crt-x64', exact=True) }}

  - name: {{ name }}-asan-x64
    version: {{ msvc_version }}
    script: bld_vs2022.bat                      # [win]
    requirements:
      run:
        - {{ pin_subpackage('vs2022-msvc-x64', exact=True) }}

  - name: {{ name }}-crt-x64
    version: {{ msvc_version }}
    script: bld_vs2022.bat                      # [win]

about:
  home: foo
  summary: foo
  description: foo
  license: MIT
  license_family: MIT
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - adriendelsalle
